spring:
  application:
    name: store
  datasource:
    url: jdbc:mariadb://localhost:3306/store?createDatabaseIfNotExist=true
    username: zaki
    password: password 
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  supported-currencies: USD,EUR,GBP
payment-gateway: paypal
mail:
  host: https://smtp.gmail.com
  port: 5761